spring:
  datasource:
    url: jdbc:mysql://xxxxx:3306/sensor_sample_db?characterEncoding=UTF-8&useServerPrepStmts=true&useSSL=false
    username: xxxx
    password: xxxx
    driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
      database: MYSQL
      hibernate:
        ddl-auto : update